#!/usr/bin/env ruby
require 'bluepill'
require 'redis'
require 'json'

BASE_DIR = File.expand_path(File.dirname(__FILE__))

def help
  puts "#{File.basename(__FILE__)} usage: [command] [options...]"
  puts "'start'"
  puts "'stop'"
  puts "'join #<channel>'"
  puts "'part #<channel>'"
  puts "'nick <nickname>'"
  puts "'say #<channel> <msg>'"
  exit
end


help if ARGV[0] == 'help'

opts = {:base_dir => File.join(BASE_DIR,".bluepill"),
        :log_file => File.join(BASE_DIR,"bluepill.log")}
controller = Bluepill::Controller.new(opts)
apps = controller.running_applications

if ARGV.size == 0
  if apps.size > 0
    app = apps.first
    puts "neuron is running."
  end
end

if ARGV[0] == 'start'
  if apps.length == 0
    cmd = "bundle exec bluepill load neuron.pill --no-privileged --base-dir #{opts[:base_dir]} --logfile #{opts[:log_file]}"
    $stderr.puts cmd
    system(cmd)
  end
  controller.handle_command('neuron', 'start', ARGV[1])
end

if ARGV[0] == 'stop'
  controller.handle_command('neuron', 'stop', ARGV[1])
  if ARGV[1].nil?
    controller.handle_command('neuron', 'quit', nil)
  end
end

if ARGV.size == 2
  msg = {"command" => ARGV[0], "message" => ARGV[1]}
end

if ARGV.size == 3
  msg = {"command" => ARGV[0], "target" => ARGV[1], "message" => ARGV[2]}
end

redis = Redis.new

if msg
  puts msg.inspect
  redis.publish :say, msg.to_json
end